# Generated by Django 6.0.5 on 2026-06-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0002_bus_empresa_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='piso',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bus',
            name='pisos',
            field=models.IntegerField(choices=[(1, '1 Piso'), (2, '2 Pisos')], default=1),
        ),
    ]
