# Generated by Django 6.0.5 on 2026-06-01 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0005_migrate_capacidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='capacidad',
        ),
    ]
