# Generated by Django 6.0.5 on 2026-06-08 01:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0007_terminal_itinerario_asiento_itinerario_ruta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.IntegerField(default=5000)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('ultimos_digitos', models.CharField(default='0000', max_length=4)),
                ('asiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boletos.asiento')),
                ('itinerario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boletos.itinerario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_compra'],
            },
        ),
    ]
