# Generated by Django 6.0.5 on 2026-06-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0008_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='fecha_viaje',
            field=models.DateField(blank=True, null=True),
        ),
    ]
