# Generated by Django 6.0.5 on 2026-06-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0009_asiento_fecha_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
