# Generated by Django 6.0.5 on 2026-06-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0010_asiento_cancelado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='asiento',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='monto',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='asientos',
            field=models.ManyToManyField(related_name='transacciones', to='boletos.asiento'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='monto_total',
            field=models.IntegerField(default=5000),
        ),
    ]
